#!/bin/bash

FILES=""

# Iterate over every file staged for commit
for FILE in $(git diff --cached --name-only -r HEAD)
do
	# Extract the file extension from the full name
	FILENAME=$(basename "$FILE")
	EXT="${FILENAME##*.}"

	# Check if the file is a source or header file
	if [ $EXT = "cpp" ] || [ $EXT = "hpp" ]
	then
		FILES+=" $FILE"
	fi
done

# Format the files
clang-format -i $FILES
