# Path to your oh-my-zsh installation.
export ZSH="/home/robaire/.oh-my-zsh"

# ZSH Config
ZSH_THEME="minimal"
HYPHEN_INSENSITIVE=true
DISABLE_AUTO_UPDATE=true

ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOCONNECT=false

BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Plugins
plugins=(tmux git rust)
source $ZSH/oh-my-zsh.sh

# Environment Variables
export EDITOR="nvim"

# Aliases
alias vim="nvim"
alias zshconfig="nvim ~/.zshrc"
alias open="xdg-open"
alias python="python3"
alias update="sudo apt update && apt list --upgradable"
alias upgrade="sudo apt upgrade -y"
