# Path to your oh-my-zsh installation.
export ZSH="/home/robaire/.oh-my-zsh"

# ZSH Config
ZSH_THEME="minimal"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"

# Plugins
plugins=(git cargo rust rustup)

source $ZSH/oh-my-zsh.sh

# Aliases
alias vim="nvim"
alias zshconfig="nvim ~/.zshrc"
alias open="xdg-open"
alias python="python3"
